Models Created from ddl and updated ddl
victorffernandes/smart-attendance-bff pull request #2
Opened 2023-10-04 23:46 UTC by victorffernandes

2023-10-04 23:56 UTC, victorfernandesuff requested changes

2023-10-04 23:56 UTC, victorfernandesuff commented on app/smartattendance/models.py
adicionar a tabela turma horário

2023-10-06 23:08 UTC, mauriciolfsilva commented
Adicionados os models e migration relacionada.
Para quem executou o comando anteriormente para criar o docker, recomendo deletar o docker e criar novamente.

2023-10-06 23:34 UTC, mauriciolfsilva approved these changes

2023-10-06 23:35 UTC, merged